project:
  type: website
  output-dir: docs

website:
  title: "@brunj7"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: blogs.qmd
        text: Blogs
      - href: trainings.qmd
        text: Trainings
      - href: packages.qmd
        text: R Packages
    right:
      - icon: github
        href: https://github.com/brunj7
        aria-label: GitHub
  page-footer:
    left: |
      Text and figures are licensed under <a href="https://creativecommons.org/licenses/by/4.0/" rel="license">CC BY 4.0</a>. Source code is available at <a href="https://github.com/brunj7/brunj7.github.io">https://github.com/brunj7/brunj7.github.io</a>.
    right: |
      If you see mistakes or want to suggest changes, please <a href="https://github.com/brunj7/brunj7.github.io/issues/new">create an issue</a> on the source repository.

format:
  html:
    theme: cosmo
    css: styles.css
    mainfont: "Bitter"
    monofont: "DM Mono"