---
title: "Introducing the Reproducible and Collaborative Lab Program"
description: |
  "This new service combines group workshops, self-paced learning and personalized coaching with a focus on collaborative coding, data management, developing scripted analytical workflows and preserving scientific products"
author:
  - name: Julien Brun
    orcid: 0000-0002-7751-6238
  - name: Greg Janée
  - name: Renata Curty
date: 2024-11-01
---

## Abstract

This program combines workshops and coaching sessions for Faculty and their Team on the following topics:

- Coding as a lab
- Managing your lab data
- Automating your analytical workflows
- Documenting & preserving things to make them reusable

Our Team will work with labs at their convenience (for example coming to a lab meeting) to foster team conversation around infrastructures and practices to make your research more reproducible, enable you to reuse your own work, and collaborate more effectively.

Examples of what we have done so far with labs:

- Helped to set up a GitHub organization to centralize the management and collaboration on their code
- Develop lab guidelines to manage & document data in a consistent way
- Map analytical workflows from raw data to scientific products

## Original post on The UCSB Current website

<https://news.ucsb.edu/in-focus/librarys-new-consultation-service-targets-campus-research-labs>

## Program website

<https://ucsb-library-research-data-services.github.io/reproducible-lab/index.html>